---
- name: Delete route
  openshift_v1_route:
    name: '{{ application_name }}'
    namespace: '{{ namespace }}'
    state: absent

- name: Delete services
  k8s_v1_service:
    name: '{{ application_name }}'
    namespace: '{{ namespace }}'
    state: absent

- name: Delete deployment configs
  openshift_v1_deployment_config:
    name: {{ application_name }}
    namespace: '{{ namespace }}'
    state: absent

- name: Delete ImageStream
  openshift_v1_image_stream:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: absent
