---
# Global constants
application_name: keycloak

keycloak_image_name: ruromero/keycloak
keycloak_image_tag: openshift-latest
realm_name: master
vendors:
  MySQL: mysql
  PostgreSQL: postgres
  MariaDB: mariadb
  Ephemeral: H2
