---
- name: "[SET UP] tmp folder"
  file:
    path: /tmp/keycloak
    state: directory

- name: "[KEYCLOAK] Deploy"
  include_tasks: deploy-keycloak.yml
  when: _apb_plan_id != 'external'

- name: "[KEYCLOAK] Set Keycloak URI"
  include_role:
    name: set-keycloak-uri

- name: "[KEYCLOAK] Provision"
  include_tasks: provision-keycloak.yml
  when: _apb_plan_id == 'external'

# New encoding task makes admin credentials available to future bind operations
- name: "[KEYCLOAK] Encode provision credentials"
  asb_encode_binding:
    fields:
      admin_username: "{{ admin_username }}"
      admin_password: "{{ admin_password }}"
      realm_name: "{{ realm_name }}"
      keycloak_uri: "{{ keycloak_uri }}"
