---
- name: "Set Keycloak URI from user defined variable"
  set_fact:
    keycloak_uri: "{{ apb_keycloak_uri }}"
  when:
    - apb_keycloak_uri is defined
    - apb_keycloak_uri != ""

- block:
  - name: Get keycloak https route
    openshift_v1_route:
      name: '{{ application_name }}'
      namespace: '{{ namespace }}'
    register: keycloak_route_raw

  - name: Set keycloak uri from route
    set_fact:
      keycloak_uri: 'https://{{ keycloak_route_raw.route.spec.host }}'

  - name: Test URL
    uri:
      url: "{{ keycloak_uri }}/auth/"
      return_content: yes
      validate_certs: no
    register: webpage
    ignore_errors: true
    retries: 2
    delay: 2
    until:
      - webpage.status == 200
      - '"Welcome to" in webpage.content'

  - block:
    - name: Get keycloak service
      k8s_v1_service:
        name: '{{ application_name }}'
        namespace: '{{ namespace }}'
      register: keycloak_service_raw

    - name: Set keycloak uri from service
      set_fact:
        keycloak_uri: 'http://{{ keycloak_service_raw.service.spec.cluster_ip }}:{{ keycloak_service_raw.service.spec.ports[0].port }}'
    when: (webpage.status != 200) or
          (not "Welcome to" in webpage.content)
  when: (not apb_keycloak_uri is defined) or (apb_keycloak_uri == "")
