- name: keycloak-apb playbook to update the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - vars/common.yml
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: update-keycloak-apb
    playbook_debug: false
