---
- name: Generate keycloak auth token
  uri:
    url: "{{ _apb_provision_creds.keycloak_uri }}/auth/realms/master/protocol/openid-connect/token"
    method: POST
    body: "client_id=admin-cli&username={{ _apb_provision_creds.admin_username }}&password={{ _apb_provision_creds.admin_password }}&grant_type=password"
    validate_certs: no
  register: keycloak_auth_response
  until: keycloak_auth_response.status == 200
  retries: 5
  delay: 2

- name: Delete client {{ _apb_bind_creds.SSO_CLIENT }} in realm {{ _apb_provision_creds.realm_name }}
  uri:
    url: "{{ _apb_provision_creds.keycloak_uri }}/auth/admin/realms/{{ _apb_provision_creds.realm_name }}/clients/{{ _apb_bind_creds.SSO_CLIENT }}"
    method: DELETE
    validate_certs: no
    headers:
      Authorization: "bearer {{ keycloak_auth_response.json.access_token }}"
    status_code: 204
    return_content: yes
